[project]
name = "sims-family-tree"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.9.3",
    "networkx>=3.4.2",
]
