name: CI - Unit tests on PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v1
        with:
          version: "0.5.7"
      - name: Install dependencies
        run: uv sync -p 3.13
      - name: pytest
        run: uv run pytest
